// Code generated by protoc-gen-go. DO NOT EDIT.
// source: location.proto

package location

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MAPSubscriberInfoInvoke struct {
	CalledSCCPAddress    string   `protobuf:"bytes,1,opt,name=CalledSCCPAddress,proto3" json:"CalledSCCPAddress,omitempty"`
	CallingSCCPAddress   string   `protobuf:"bytes,2,opt,name=CallingSCCPAddress,proto3" json:"CallingSCCPAddress,omitempty"`
	OTID                 uint32   `protobuf:"varint,3,opt,name=OTID,proto3" json:"OTID,omitempty"`
	DTID                 uint32   `protobuf:"varint,4,opt,name=DTID,proto3" json:"DTID,omitempty"`
	VLR                  string   `protobuf:"bytes,5,opt,name=VLR,proto3" json:"VLR,omitempty"`
	MSC                  string   `protobuf:"bytes,6,opt,name=MSC,proto3" json:"MSC,omitempty"`
	HLR                  string   `protobuf:"bytes,7,opt,name=HLR,proto3" json:"HLR,omitempty"`
	MME                  string   `protobuf:"bytes,8,opt,name=MME,proto3" json:"MME,omitempty"`
	MSISDN               string   `protobuf:"bytes,9,opt,name=MSISDN,proto3" json:"MSISDN,omitempty"`
	IMSI                 string   `protobuf:"bytes,10,opt,name=IMSI,proto3" json:"IMSI,omitempty"`
	IMEI                 string   `protobuf:"bytes,11,opt,name=IMEI,proto3" json:"IMEI,omitempty"`
	Message              string   `protobuf:"bytes,12,opt,name=Message,proto3" json:"Message,omitempty"`
	Protocol             string   `protobuf:"bytes,13,opt,name=Protocol,proto3" json:"Protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MAPSubscriberInfoInvoke) Reset()         { *m = MAPSubscriberInfoInvoke{} }
func (m *MAPSubscriberInfoInvoke) String() string { return proto.CompactTextString(m) }
func (*MAPSubscriberInfoInvoke) ProtoMessage()    {}
func (*MAPSubscriberInfoInvoke) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f35158dcf9f2c, []int{0}
}

func (m *MAPSubscriberInfoInvoke) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MAPSubscriberInfoInvoke.Unmarshal(m, b)
}
func (m *MAPSubscriberInfoInvoke) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MAPSubscriberInfoInvoke.Marshal(b, m, deterministic)
}
func (m *MAPSubscriberInfoInvoke) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MAPSubscriberInfoInvoke.Merge(m, src)
}
func (m *MAPSubscriberInfoInvoke) XXX_Size() int {
	return xxx_messageInfo_MAPSubscriberInfoInvoke.Size(m)
}
func (m *MAPSubscriberInfoInvoke) XXX_DiscardUnknown() {
	xxx_messageInfo_MAPSubscriberInfoInvoke.DiscardUnknown(m)
}

var xxx_messageInfo_MAPSubscriberInfoInvoke proto.InternalMessageInfo

func (m *MAPSubscriberInfoInvoke) GetCalledSCCPAddress() string {
	if m != nil {
		return m.CalledSCCPAddress
	}
	return ""
}

func (m *MAPSubscriberInfoInvoke) GetCallingSCCPAddress() string {
	if m != nil {
		return m.CallingSCCPAddress
	}
	return ""
}

func (m *MAPSubscriberInfoInvoke) GetOTID() uint32 {
	if m != nil {
		return m.OTID
	}
	return 0
}

func (m *MAPSubscriberInfoInvoke) GetDTID() uint32 {
	if m != nil {
		return m.DTID
	}
	return 0
}

func (m *MAPSubscriberInfoInvoke) GetVLR() string {
	if m != nil {
		return m.VLR
	}
	return ""
}

func (m *MAPSubscriberInfoInvoke) GetMSC() string {
	if m != nil {
		return m.MSC
	}
	return ""
}

func (m *MAPSubscriberInfoInvoke) GetHLR() string {
	if m != nil {
		return m.HLR
	}
	return ""
}

func (m *MAPSubscriberInfoInvoke) GetMME() string {
	if m != nil {
		return m.MME
	}
	return ""
}

func (m *MAPSubscriberInfoInvoke) GetMSISDN() string {
	if m != nil {
		return m.MSISDN
	}
	return ""
}

func (m *MAPSubscriberInfoInvoke) GetIMSI() string {
	if m != nil {
		return m.IMSI
	}
	return ""
}

func (m *MAPSubscriberInfoInvoke) GetIMEI() string {
	if m != nil {
		return m.IMEI
	}
	return ""
}

func (m *MAPSubscriberInfoInvoke) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *MAPSubscriberInfoInvoke) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

type MAPSubscriberInfoResult struct {
	CalledSCCPAddress    string   `protobuf:"bytes,1,opt,name=CalledSCCPAddress,proto3" json:"CalledSCCPAddress,omitempty"`
	CallingSCCPAddress   string   `protobuf:"bytes,2,opt,name=CallingSCCPAddress,proto3" json:"CallingSCCPAddress,omitempty"`
	OTID                 uint32   `protobuf:"varint,3,opt,name=OTID,proto3" json:"OTID,omitempty"`
	DTID                 uint32   `protobuf:"varint,4,opt,name=DTID,proto3" json:"DTID,omitempty"`
	VLR                  string   `protobuf:"bytes,5,opt,name=VLR,proto3" json:"VLR,omitempty"`
	MSC                  string   `protobuf:"bytes,6,opt,name=MSC,proto3" json:"MSC,omitempty"`
	HLR                  string   `protobuf:"bytes,7,opt,name=HLR,proto3" json:"HLR,omitempty"`
	MME                  string   `protobuf:"bytes,8,opt,name=MME,proto3" json:"MME,omitempty"`
	MSISDN               string   `protobuf:"bytes,9,opt,name=MSISDN,proto3" json:"MSISDN,omitempty"`
	IMSI                 string   `protobuf:"bytes,10,opt,name=IMSI,proto3" json:"IMSI,omitempty"`
	IMEI                 string   `protobuf:"bytes,11,opt,name=IMEI,proto3" json:"IMEI,omitempty"`
	Message              string   `protobuf:"bytes,12,opt,name=Message,proto3" json:"Message,omitempty"`
	Protocol             string   `protobuf:"bytes,13,opt,name=Protocol,proto3" json:"Protocol,omitempty"`
	LocationNumber       string   `protobuf:"bytes,14,opt,name=LocationNumber,proto3" json:"LocationNumber,omitempty"`
	MCC                  uint32   `protobuf:"varint,15,opt,name=MCC,proto3" json:"MCC,omitempty"`
	MNC                  uint32   `protobuf:"varint,16,opt,name=MNC,proto3" json:"MNC,omitempty"`
	LAC                  uint32   `protobuf:"varint,17,opt,name=LAC,proto3" json:"LAC,omitempty"`
	CI                   uint32   `protobuf:"varint,18,opt,name=CI,proto3" json:"CI,omitempty"`
	Latitude             float64  `protobuf:"fixed64,19,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,20,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	Radius               uint32   `protobuf:"varint,21,opt,name=Radius,proto3" json:"Radius,omitempty"`
	Age                  uint32   `protobuf:"varint,22,opt,name=Age,proto3" json:"Age,omitempty"`
	Status               string   `protobuf:"bytes,23,opt,name=Status,proto3" json:"Status,omitempty"`
	Error                string   `protobuf:"bytes,24,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MAPSubscriberInfoResult) Reset()         { *m = MAPSubscriberInfoResult{} }
func (m *MAPSubscriberInfoResult) String() string { return proto.CompactTextString(m) }
func (*MAPSubscriberInfoResult) ProtoMessage()    {}
func (*MAPSubscriberInfoResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f35158dcf9f2c, []int{1}
}

func (m *MAPSubscriberInfoResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MAPSubscriberInfoResult.Unmarshal(m, b)
}
func (m *MAPSubscriberInfoResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MAPSubscriberInfoResult.Marshal(b, m, deterministic)
}
func (m *MAPSubscriberInfoResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MAPSubscriberInfoResult.Merge(m, src)
}
func (m *MAPSubscriberInfoResult) XXX_Size() int {
	return xxx_messageInfo_MAPSubscriberInfoResult.Size(m)
}
func (m *MAPSubscriberInfoResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MAPSubscriberInfoResult.DiscardUnknown(m)
}

var xxx_messageInfo_MAPSubscriberInfoResult proto.InternalMessageInfo

func (m *MAPSubscriberInfoResult) GetCalledSCCPAddress() string {
	if m != nil {
		return m.CalledSCCPAddress
	}
	return ""
}

func (m *MAPSubscriberInfoResult) GetCallingSCCPAddress() string {
	if m != nil {
		return m.CallingSCCPAddress
	}
	return ""
}

func (m *MAPSubscriberInfoResult) GetOTID() uint32 {
	if m != nil {
		return m.OTID
	}
	return 0
}

func (m *MAPSubscriberInfoResult) GetDTID() uint32 {
	if m != nil {
		return m.DTID
	}
	return 0
}

func (m *MAPSubscriberInfoResult) GetVLR() string {
	if m != nil {
		return m.VLR
	}
	return ""
}

func (m *MAPSubscriberInfoResult) GetMSC() string {
	if m != nil {
		return m.MSC
	}
	return ""
}

func (m *MAPSubscriberInfoResult) GetHLR() string {
	if m != nil {
		return m.HLR
	}
	return ""
}

func (m *MAPSubscriberInfoResult) GetMME() string {
	if m != nil {
		return m.MME
	}
	return ""
}

func (m *MAPSubscriberInfoResult) GetMSISDN() string {
	if m != nil {
		return m.MSISDN
	}
	return ""
}

func (m *MAPSubscriberInfoResult) GetIMSI() string {
	if m != nil {
		return m.IMSI
	}
	return ""
}

func (m *MAPSubscriberInfoResult) GetIMEI() string {
	if m != nil {
		return m.IMEI
	}
	return ""
}

func (m *MAPSubscriberInfoResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *MAPSubscriberInfoResult) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *MAPSubscriberInfoResult) GetLocationNumber() string {
	if m != nil {
		return m.LocationNumber
	}
	return ""
}

func (m *MAPSubscriberInfoResult) GetMCC() uint32 {
	if m != nil {
		return m.MCC
	}
	return 0
}

func (m *MAPSubscriberInfoResult) GetMNC() uint32 {
	if m != nil {
		return m.MNC
	}
	return 0
}

func (m *MAPSubscriberInfoResult) GetLAC() uint32 {
	if m != nil {
		return m.LAC
	}
	return 0
}

func (m *MAPSubscriberInfoResult) GetCI() uint32 {
	if m != nil {
		return m.CI
	}
	return 0
}

func (m *MAPSubscriberInfoResult) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *MAPSubscriberInfoResult) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *MAPSubscriberInfoResult) GetRadius() uint32 {
	if m != nil {
		return m.Radius
	}
	return 0
}

func (m *MAPSubscriberInfoResult) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *MAPSubscriberInfoResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *MAPSubscriberInfoResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Pong struct {
	Msg                  uint32   `protobuf:"varint,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f35158dcf9f2c, []int{2}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetMsg() uint32 {
	if m != nil {
		return m.Msg
	}
	return 0
}

func init() {
	proto.RegisterType((*MAPSubscriberInfoInvoke)(nil), "location.MAPSubscriberInfoInvoke")
	proto.RegisterType((*MAPSubscriberInfoResult)(nil), "location.MAPSubscriberInfoResult")
	proto.RegisterType((*Pong)(nil), "location.Pong")
}

func init() {
	proto.RegisterFile("location.proto", fileDescriptor_4f0f35158dcf9f2c)
}

var fileDescriptor_4f0f35158dcf9f2c = []byte{
	// 503 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x94, 0xc1, 0x6e, 0xd3, 0x4c,
	0x10, 0xc7, 0x3f, 0x27, 0x69, 0x9a, 0xec, 0x47, 0x43, 0xbb, 0x94, 0x74, 0x94, 0x72, 0x48, 0x73,
	0x40, 0x39, 0x20, 0x57, 0x82, 0x27, 0xb0, 0x36, 0x96, 0xba, 0x92, 0x1d, 0x22, 0x1b, 0x71, 0xe0,
	0x66, 0xc7, 0xdb, 0x55, 0x84, 0xe3, 0xad, 0x76, 0x6d, 0x24, 0xde, 0x80, 0x97, 0xec, 0xbb, 0xa0,
	0x9d, 0x75, 0x02, 0x82, 0xa6, 0x1c, 0x80, 0x1b, 0xb7, 0xf9, 0xff, 0xe6, 0xaf, 0x19, 0xcf, 0x68,
	0x3d, 0x64, 0x54, 0xaa, 0x75, 0x56, 0x6f, 0x54, 0xe5, 0xdf, 0x69, 0x55, 0x2b, 0x3a, 0xd8, 0xe9,
	0xc9, 0xa5, 0x54, 0x4a, 0x96, 0xe2, 0x1a, 0x79, 0xde, 0xdc, 0x5e, 0x8b, 0xed, 0x5d, 0xfd, 0xd9,
	0xd9, 0x66, 0xf7, 0x1d, 0x72, 0x11, 0x07, 0xab, 0xb4, 0xc9, 0xcd, 0x5a, 0x6f, 0x72, 0xa1, 0x79,
	0x75, 0xab, 0x78, 0xf5, 0x49, 0x7d, 0x14, 0xf4, 0x15, 0x39, 0x63, 0x59, 0x59, 0x8a, 0x22, 0x65,
	0x6c, 0x15, 0x14, 0x85, 0x16, 0xc6, 0x80, 0x37, 0xf5, 0xe6, 0xc3, 0xe4, 0xe7, 0x04, 0xf5, 0x09,
	0xb5, 0x70, 0x53, 0xc9, 0xef, 0xed, 0x1d, 0xb4, 0x3f, 0x90, 0xa1, 0x94, 0xf4, 0xde, 0xbe, 0xe3,
	0x0b, 0xe8, 0x4e, 0xbd, 0xf9, 0x49, 0x82, 0xb1, 0x65, 0x0b, 0xcb, 0x7a, 0x8e, 0xd9, 0x98, 0x9e,
	0x92, 0xee, 0xfb, 0x28, 0x81, 0x23, 0x2c, 0x64, 0x43, 0x4b, 0xe2, 0x94, 0x41, 0xdf, 0x91, 0x38,
	0x65, 0x96, 0xdc, 0x44, 0x09, 0x1c, 0x3b, 0x72, 0xd3, 0x7a, 0xe2, 0x10, 0x06, 0xad, 0x27, 0x0e,
	0xe9, 0x98, 0xf4, 0xe3, 0x94, 0xa7, 0x8b, 0x25, 0x0c, 0x11, 0xb6, 0xca, 0xf6, 0xe4, 0x71, 0xca,
	0x81, 0x20, 0xc5, 0xd8, 0xb1, 0x90, 0xc3, 0xff, 0x3b, 0x16, 0x72, 0x0a, 0xe4, 0x38, 0x16, 0xc6,
	0x64, 0x52, 0xc0, 0x13, 0xc4, 0x3b, 0x49, 0x27, 0x64, 0xb0, 0xb2, 0xcb, 0x5c, 0xab, 0x12, 0x4e,
	0x30, 0xb5, 0xd7, 0xb3, 0xfb, 0xde, 0x03, 0xfb, 0x4d, 0x84, 0x69, 0xca, 0xfa, 0xdf, 0x7e, 0x7f,
	0x7f, 0xbf, 0xf4, 0x25, 0x19, 0x45, 0xed, 0x43, 0x5f, 0x36, 0xdb, 0x5c, 0x68, 0x18, 0xa1, 0xe3,
	0x07, 0x8a, 0xdf, 0xcb, 0x18, 0x3c, 0xc5, 0xc1, 0x6d, 0x88, 0x64, 0xc9, 0xe0, 0xb4, 0x25, 0x4b,
	0x24, 0x51, 0xc0, 0xe0, 0xcc, 0x91, 0x28, 0x60, 0x74, 0x44, 0x3a, 0x8c, 0x03, 0x45, 0xd0, 0x61,
	0xdc, 0x7e, 0x49, 0x94, 0xd5, 0x9b, 0xba, 0x29, 0x04, 0x3c, 0x9b, 0x7a, 0x73, 0x2f, 0xd9, 0x6b,
	0xfa, 0x82, 0x0c, 0x23, 0x55, 0x49, 0x97, 0x3c, 0xc7, 0xe4, 0x37, 0x60, 0xb7, 0x93, 0x64, 0xc5,
	0xa6, 0x31, 0xf0, 0x1c, 0xab, 0xb5, 0xca, 0xf6, 0x0c, 0xa4, 0x80, 0xb1, 0xeb, 0x19, 0x48, 0x74,
	0xa6, 0x75, 0x56, 0x37, 0x06, 0x2e, 0xdc, 0x1e, 0x9d, 0xa2, 0xe7, 0xe4, 0x28, 0xd4, 0x5a, 0x69,
	0x00, 0xc4, 0x4e, 0xcc, 0x80, 0xf4, 0x56, 0xaa, 0x92, 0x38, 0x8d, 0x91, 0xf8, 0x7a, 0xec, 0x34,
	0x46, 0xbe, 0xfe, 0xd2, 0x25, 0xfd, 0x48, 0x65, 0x85, 0xd0, 0xf4, 0x03, 0xb9, 0xb4, 0xd1, 0xa1,
	0xff, 0xfc, 0xca, 0xdf, 0xdf, 0x8e, 0x03, 0x96, 0xc9, 0xd8, 0x77, 0x47, 0xc4, 0xdf, 0x1d, 0x11,
	0x3f, 0xb4, 0x47, 0x64, 0xf6, 0xdf, 0xc1, 0xda, 0xed, 0x1b, 0x7f, 0xac, 0xb6, 0xb3, 0x3c, 0x52,
	0x3b, 0x27, 0x57, 0xb6, 0x76, 0x5a, 0x6b, 0x91, 0x6d, 0xff, 0xc6, 0xd7, 0xcf, 0xbd, 0x5f, 0xf4,
	0xf8, 0x03, 0x53, 0xcc, 0xbd, 0xbc, 0x8f, 0xec, 0xcd, 0xd7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x52,
	0xdb, 0x74, 0xd4, 0xa4, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LoaderClient is the client API for Loader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoaderClient interface {
	LoadMAPSubscriberInfoInvoke(ctx context.Context, in *MAPSubscriberInfoInvoke, opts ...grpc.CallOption) (*empty.Empty, error)
	LoadMAPSubscriberInfoResult(ctx context.Context, in *MAPSubscriberInfoResult, opts ...grpc.CallOption) (*empty.Empty, error)
	LoadStreamMAPSubscriberInfoInvoke(ctx context.Context, opts ...grpc.CallOption) (Loader_LoadStreamMAPSubscriberInfoInvokeClient, error)
	LoadStreamMAPSubscriberInfoResult(ctx context.Context, opts ...grpc.CallOption) (Loader_LoadStreamMAPSubscriberInfoResultClient, error)
}

type loaderClient struct {
	cc grpc.ClientConnInterface
}

func NewLoaderClient(cc grpc.ClientConnInterface) LoaderClient {
	return &loaderClient{cc}
}

func (c *loaderClient) LoadMAPSubscriberInfoInvoke(ctx context.Context, in *MAPSubscriberInfoInvoke, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/location.Loader/LoadMAPSubscriberInfoInvoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loaderClient) LoadMAPSubscriberInfoResult(ctx context.Context, in *MAPSubscriberInfoResult, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/location.Loader/LoadMAPSubscriberInfoResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loaderClient) LoadStreamMAPSubscriberInfoInvoke(ctx context.Context, opts ...grpc.CallOption) (Loader_LoadStreamMAPSubscriberInfoInvokeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Loader_serviceDesc.Streams[0], "/location.Loader/LoadStreamMAPSubscriberInfoInvoke", opts...)
	if err != nil {
		return nil, err
	}
	x := &loaderLoadStreamMAPSubscriberInfoInvokeClient{stream}
	return x, nil
}

type Loader_LoadStreamMAPSubscriberInfoInvokeClient interface {
	Send(*MAPSubscriberInfoInvoke) error
	CloseAndRecv() (*empty.Empty, error)
	grpc.ClientStream
}

type loaderLoadStreamMAPSubscriberInfoInvokeClient struct {
	grpc.ClientStream
}

func (x *loaderLoadStreamMAPSubscriberInfoInvokeClient) Send(m *MAPSubscriberInfoInvoke) error {
	return x.ClientStream.SendMsg(m)
}

func (x *loaderLoadStreamMAPSubscriberInfoInvokeClient) CloseAndRecv() (*empty.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(empty.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *loaderClient) LoadStreamMAPSubscriberInfoResult(ctx context.Context, opts ...grpc.CallOption) (Loader_LoadStreamMAPSubscriberInfoResultClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Loader_serviceDesc.Streams[1], "/location.Loader/LoadStreamMAPSubscriberInfoResult", opts...)
	if err != nil {
		return nil, err
	}
	x := &loaderLoadStreamMAPSubscriberInfoResultClient{stream}
	return x, nil
}

type Loader_LoadStreamMAPSubscriberInfoResultClient interface {
	Send(*MAPSubscriberInfoResult) error
	CloseAndRecv() (*empty.Empty, error)
	grpc.ClientStream
}

type loaderLoadStreamMAPSubscriberInfoResultClient struct {
	grpc.ClientStream
}

func (x *loaderLoadStreamMAPSubscriberInfoResultClient) Send(m *MAPSubscriberInfoResult) error {
	return x.ClientStream.SendMsg(m)
}

func (x *loaderLoadStreamMAPSubscriberInfoResultClient) CloseAndRecv() (*empty.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(empty.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LoaderServer is the server API for Loader service.
type LoaderServer interface {
	LoadMAPSubscriberInfoInvoke(context.Context, *MAPSubscriberInfoInvoke) (*empty.Empty, error)
	LoadMAPSubscriberInfoResult(context.Context, *MAPSubscriberInfoResult) (*empty.Empty, error)
	LoadStreamMAPSubscriberInfoInvoke(Loader_LoadStreamMAPSubscriberInfoInvokeServer) error
	LoadStreamMAPSubscriberInfoResult(Loader_LoadStreamMAPSubscriberInfoResultServer) error
}

// UnimplementedLoaderServer can be embedded to have forward compatible implementations.
type UnimplementedLoaderServer struct {
}

func (*UnimplementedLoaderServer) LoadMAPSubscriberInfoInvoke(ctx context.Context, req *MAPSubscriberInfoInvoke) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadMAPSubscriberInfoInvoke not implemented")
}
func (*UnimplementedLoaderServer) LoadMAPSubscriberInfoResult(ctx context.Context, req *MAPSubscriberInfoResult) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadMAPSubscriberInfoResult not implemented")
}
func (*UnimplementedLoaderServer) LoadStreamMAPSubscriberInfoInvoke(srv Loader_LoadStreamMAPSubscriberInfoInvokeServer) error {
	return status.Errorf(codes.Unimplemented, "method LoadStreamMAPSubscriberInfoInvoke not implemented")
}
func (*UnimplementedLoaderServer) LoadStreamMAPSubscriberInfoResult(srv Loader_LoadStreamMAPSubscriberInfoResultServer) error {
	return status.Errorf(codes.Unimplemented, "method LoadStreamMAPSubscriberInfoResult not implemented")
}

func RegisterLoaderServer(s *grpc.Server, srv LoaderServer) {
	s.RegisterService(&_Loader_serviceDesc, srv)
}

func _Loader_LoadMAPSubscriberInfoInvoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MAPSubscriberInfoInvoke)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoaderServer).LoadMAPSubscriberInfoInvoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/location.Loader/LoadMAPSubscriberInfoInvoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoaderServer).LoadMAPSubscriberInfoInvoke(ctx, req.(*MAPSubscriberInfoInvoke))
	}
	return interceptor(ctx, in, info, handler)
}

func _Loader_LoadMAPSubscriberInfoResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MAPSubscriberInfoResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoaderServer).LoadMAPSubscriberInfoResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/location.Loader/LoadMAPSubscriberInfoResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoaderServer).LoadMAPSubscriberInfoResult(ctx, req.(*MAPSubscriberInfoResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _Loader_LoadStreamMAPSubscriberInfoInvoke_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LoaderServer).LoadStreamMAPSubscriberInfoInvoke(&loaderLoadStreamMAPSubscriberInfoInvokeServer{stream})
}

type Loader_LoadStreamMAPSubscriberInfoInvokeServer interface {
	SendAndClose(*empty.Empty) error
	Recv() (*MAPSubscriberInfoInvoke, error)
	grpc.ServerStream
}

type loaderLoadStreamMAPSubscriberInfoInvokeServer struct {
	grpc.ServerStream
}

func (x *loaderLoadStreamMAPSubscriberInfoInvokeServer) SendAndClose(m *empty.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *loaderLoadStreamMAPSubscriberInfoInvokeServer) Recv() (*MAPSubscriberInfoInvoke, error) {
	m := new(MAPSubscriberInfoInvoke)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Loader_LoadStreamMAPSubscriberInfoResult_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LoaderServer).LoadStreamMAPSubscriberInfoResult(&loaderLoadStreamMAPSubscriberInfoResultServer{stream})
}

type Loader_LoadStreamMAPSubscriberInfoResultServer interface {
	SendAndClose(*empty.Empty) error
	Recv() (*MAPSubscriberInfoResult, error)
	grpc.ServerStream
}

type loaderLoadStreamMAPSubscriberInfoResultServer struct {
	grpc.ServerStream
}

func (x *loaderLoadStreamMAPSubscriberInfoResultServer) SendAndClose(m *empty.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *loaderLoadStreamMAPSubscriberInfoResultServer) Recv() (*MAPSubscriberInfoResult, error) {
	m := new(MAPSubscriberInfoResult)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Loader_serviceDesc = grpc.ServiceDesc{
	ServiceName: "location.Loader",
	HandlerType: (*LoaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadMAPSubscriberInfoInvoke",
			Handler:    _Loader_LoadMAPSubscriberInfoInvoke_Handler,
		},
		{
			MethodName: "LoadMAPSubscriberInfoResult",
			Handler:    _Loader_LoadMAPSubscriberInfoResult_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LoadStreamMAPSubscriberInfoInvoke",
			Handler:       _Loader_LoadStreamMAPSubscriberInfoInvoke_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "LoadStreamMAPSubscriberInfoResult",
			Handler:       _Loader_LoadStreamMAPSubscriberInfoResult_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "location.proto",
}
