// Code generated by protoc-gen-go. DO NOT EDIT.
// source: location.proto

package location

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MAPSubscriberInfoInvoke struct {
	CalledSCCPAddress    string   `protobuf:"bytes,1,opt,name=CalledSCCPAddress,proto3" json:"CalledSCCPAddress,omitempty"`
	CallingSCCPAddress   string   `protobuf:"bytes,2,opt,name=CallingSCCPAddress,proto3" json:"CallingSCCPAddress,omitempty"`
	OTID                 uint32   `protobuf:"varint,3,opt,name=OTID,proto3" json:"OTID,omitempty"`
	DTID                 uint32   `protobuf:"varint,4,opt,name=DTID,proto3" json:"DTID,omitempty"`
	VLRNumber            string   `protobuf:"bytes,5,opt,name=VLRNumber,proto3" json:"VLRNumber,omitempty"`
	MSISDN               string   `protobuf:"bytes,6,opt,name=MSISDN,proto3" json:"MSISDN,omitempty"`
	IMSI                 string   `protobuf:"bytes,7,opt,name=IMSI,proto3" json:"IMSI,omitempty"`
	MAPMessage           string   `protobuf:"bytes,8,opt,name=MAPMessage,proto3" json:"MAPMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MAPSubscriberInfoInvoke) Reset()         { *m = MAPSubscriberInfoInvoke{} }
func (m *MAPSubscriberInfoInvoke) String() string { return proto.CompactTextString(m) }
func (*MAPSubscriberInfoInvoke) ProtoMessage()    {}
func (*MAPSubscriberInfoInvoke) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f35158dcf9f2c, []int{0}
}

func (m *MAPSubscriberInfoInvoke) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MAPSubscriberInfoInvoke.Unmarshal(m, b)
}
func (m *MAPSubscriberInfoInvoke) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MAPSubscriberInfoInvoke.Marshal(b, m, deterministic)
}
func (m *MAPSubscriberInfoInvoke) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MAPSubscriberInfoInvoke.Merge(m, src)
}
func (m *MAPSubscriberInfoInvoke) XXX_Size() int {
	return xxx_messageInfo_MAPSubscriberInfoInvoke.Size(m)
}
func (m *MAPSubscriberInfoInvoke) XXX_DiscardUnknown() {
	xxx_messageInfo_MAPSubscriberInfoInvoke.DiscardUnknown(m)
}

var xxx_messageInfo_MAPSubscriberInfoInvoke proto.InternalMessageInfo

func (m *MAPSubscriberInfoInvoke) GetCalledSCCPAddress() string {
	if m != nil {
		return m.CalledSCCPAddress
	}
	return ""
}

func (m *MAPSubscriberInfoInvoke) GetCallingSCCPAddress() string {
	if m != nil {
		return m.CallingSCCPAddress
	}
	return ""
}

func (m *MAPSubscriberInfoInvoke) GetOTID() uint32 {
	if m != nil {
		return m.OTID
	}
	return 0
}

func (m *MAPSubscriberInfoInvoke) GetDTID() uint32 {
	if m != nil {
		return m.DTID
	}
	return 0
}

func (m *MAPSubscriberInfoInvoke) GetVLRNumber() string {
	if m != nil {
		return m.VLRNumber
	}
	return ""
}

func (m *MAPSubscriberInfoInvoke) GetMSISDN() string {
	if m != nil {
		return m.MSISDN
	}
	return ""
}

func (m *MAPSubscriberInfoInvoke) GetIMSI() string {
	if m != nil {
		return m.IMSI
	}
	return ""
}

func (m *MAPSubscriberInfoInvoke) GetMAPMessage() string {
	if m != nil {
		return m.MAPMessage
	}
	return ""
}

type MAPSubscriberInfoResult struct {
	CalledSCCPAddress    string   `protobuf:"bytes,1,opt,name=CalledSCCPAddress,proto3" json:"CalledSCCPAddress,omitempty"`
	CallingSCCPAddress   string   `protobuf:"bytes,2,opt,name=CallingSCCPAddress,proto3" json:"CallingSCCPAddress,omitempty"`
	OTID                 uint32   `protobuf:"varint,3,opt,name=OTID,proto3" json:"OTID,omitempty"`
	DTID                 uint32   `protobuf:"varint,4,opt,name=DTID,proto3" json:"DTID,omitempty"`
	VLRNumber            string   `protobuf:"bytes,5,opt,name=VLRNumber,proto3" json:"VLRNumber,omitempty"`
	MSISDN               string   `protobuf:"bytes,6,opt,name=MSISDN,proto3" json:"MSISDN,omitempty"`
	IMSI                 string   `protobuf:"bytes,7,opt,name=IMSI,proto3" json:"IMSI,omitempty"`
	MAPMessage           string   `protobuf:"bytes,8,opt,name=MAPMessage,proto3" json:"MAPMessage,omitempty"`
	LocationNumber       string   `protobuf:"bytes,9,opt,name=LocationNumber,proto3" json:"LocationNumber,omitempty"`
	MCC                  uint32   `protobuf:"varint,10,opt,name=MCC,proto3" json:"MCC,omitempty"`
	MNC                  uint32   `protobuf:"varint,11,opt,name=MNC,proto3" json:"MNC,omitempty"`
	LAC                  uint32   `protobuf:"varint,12,opt,name=LAC,proto3" json:"LAC,omitempty"`
	CI                   uint32   `protobuf:"varint,13,opt,name=CI,proto3" json:"CI,omitempty"`
	Age                  uint32   `protobuf:"varint,14,opt,name=Age,proto3" json:"Age,omitempty"`
	Status               string   `protobuf:"bytes,15,opt,name=Status,proto3" json:"Status,omitempty"`
	Error                string   `protobuf:"bytes,16,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MAPSubscriberInfoResult) Reset()         { *m = MAPSubscriberInfoResult{} }
func (m *MAPSubscriberInfoResult) String() string { return proto.CompactTextString(m) }
func (*MAPSubscriberInfoResult) ProtoMessage()    {}
func (*MAPSubscriberInfoResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f35158dcf9f2c, []int{1}
}

func (m *MAPSubscriberInfoResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MAPSubscriberInfoResult.Unmarshal(m, b)
}
func (m *MAPSubscriberInfoResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MAPSubscriberInfoResult.Marshal(b, m, deterministic)
}
func (m *MAPSubscriberInfoResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MAPSubscriberInfoResult.Merge(m, src)
}
func (m *MAPSubscriberInfoResult) XXX_Size() int {
	return xxx_messageInfo_MAPSubscriberInfoResult.Size(m)
}
func (m *MAPSubscriberInfoResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MAPSubscriberInfoResult.DiscardUnknown(m)
}

var xxx_messageInfo_MAPSubscriberInfoResult proto.InternalMessageInfo

func (m *MAPSubscriberInfoResult) GetCalledSCCPAddress() string {
	if m != nil {
		return m.CalledSCCPAddress
	}
	return ""
}

func (m *MAPSubscriberInfoResult) GetCallingSCCPAddress() string {
	if m != nil {
		return m.CallingSCCPAddress
	}
	return ""
}

func (m *MAPSubscriberInfoResult) GetOTID() uint32 {
	if m != nil {
		return m.OTID
	}
	return 0
}

func (m *MAPSubscriberInfoResult) GetDTID() uint32 {
	if m != nil {
		return m.DTID
	}
	return 0
}

func (m *MAPSubscriberInfoResult) GetVLRNumber() string {
	if m != nil {
		return m.VLRNumber
	}
	return ""
}

func (m *MAPSubscriberInfoResult) GetMSISDN() string {
	if m != nil {
		return m.MSISDN
	}
	return ""
}

func (m *MAPSubscriberInfoResult) GetIMSI() string {
	if m != nil {
		return m.IMSI
	}
	return ""
}

func (m *MAPSubscriberInfoResult) GetMAPMessage() string {
	if m != nil {
		return m.MAPMessage
	}
	return ""
}

func (m *MAPSubscriberInfoResult) GetLocationNumber() string {
	if m != nil {
		return m.LocationNumber
	}
	return ""
}

func (m *MAPSubscriberInfoResult) GetMCC() uint32 {
	if m != nil {
		return m.MCC
	}
	return 0
}

func (m *MAPSubscriberInfoResult) GetMNC() uint32 {
	if m != nil {
		return m.MNC
	}
	return 0
}

func (m *MAPSubscriberInfoResult) GetLAC() uint32 {
	if m != nil {
		return m.LAC
	}
	return 0
}

func (m *MAPSubscriberInfoResult) GetCI() uint32 {
	if m != nil {
		return m.CI
	}
	return 0
}

func (m *MAPSubscriberInfoResult) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *MAPSubscriberInfoResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *MAPSubscriberInfoResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Pong struct {
	Msg                  uint32   `protobuf:"varint,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f35158dcf9f2c, []int{2}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetMsg() uint32 {
	if m != nil {
		return m.Msg
	}
	return 0
}

func init() {
	proto.RegisterType((*MAPSubscriberInfoInvoke)(nil), "location.MAPSubscriberInfoInvoke")
	proto.RegisterType((*MAPSubscriberInfoResult)(nil), "location.MAPSubscriberInfoResult")
	proto.RegisterType((*Pong)(nil), "location.Pong")
}

func init() { proto.RegisterFile("location.proto", fileDescriptor_4f0f35158dcf9f2c) }

var fileDescriptor_4f0f35158dcf9f2c = []byte{
	// 376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x93, 0xc1, 0x6e, 0x9b, 0x40,
	0x10, 0x86, 0x0b, 0xb6, 0xa9, 0x3d, 0xad, 0xa9, 0xbb, 0xaa, 0xda, 0x55, 0x5b, 0x55, 0x2e, 0x87,
	0xca, 0x87, 0xca, 0x87, 0xe4, 0x09, 0xd0, 0x3a, 0x87, 0x95, 0x80, 0x20, 0x88, 0x72, 0x07, 0xb3,
	0x41, 0x56, 0x08, 0x1b, 0xed, 0x42, 0xde, 0x21, 0x6f, 0x93, 0x5b, 0x5e, 0x2f, 0xda, 0x81, 0xc4,
	0x56, 0x6c, 0xe7, 0x05, 0x72, 0xfb, 0xe7, 0x9b, 0x5f, 0xff, 0xb0, 0xcb, 0x2c, 0xb8, 0x95, 0x5c,
	0x67, 0xcd, 0x46, 0xd6, 0xcb, 0x5b, 0x25, 0x1b, 0x49, 0xc6, 0xcf, 0xb5, 0x77, 0x6f, 0xc3, 0x8f,
	0xd0, 0x8f, 0xd3, 0x36, 0xd7, 0x6b, 0xb5, 0xc9, 0x85, 0xe2, 0xf5, 0x95, 0xe4, 0xf5, 0x9d, 0xbc,
	0x16, 0xe4, 0x3f, 0x7c, 0x65, 0x59, 0x55, 0x89, 0x22, 0x65, 0x2c, 0xf6, 0x8b, 0x42, 0x09, 0xad,
	0xa9, 0x35, 0xb7, 0x16, 0x93, 0x64, 0xbf, 0x41, 0x96, 0x40, 0x0c, 0xdc, 0xd4, 0xe5, 0xae, 0xdd,
	0x46, 0xfb, 0x81, 0x0e, 0x21, 0x30, 0x3c, 0xbf, 0xe0, 0x2b, 0x3a, 0x98, 0x5b, 0x8b, 0x69, 0x82,
	0xda, 0xb0, 0x95, 0x61, 0xc3, 0x8e, 0x19, 0x4d, 0x7e, 0xc3, 0xe4, 0x32, 0x48, 0xa2, 0xf6, 0x26,
	0x17, 0x8a, 0x8e, 0x30, 0x6e, 0x0b, 0xc8, 0x77, 0x70, 0xc2, 0x94, 0xa7, 0xab, 0x88, 0x3a, 0xd8,
	0xea, 0x2b, 0x93, 0xc4, 0xc3, 0x94, 0xd3, 0x8f, 0x48, 0x51, 0x93, 0x3f, 0x00, 0xa1, 0x1f, 0x87,
	0x42, 0xeb, 0xac, 0x14, 0x74, 0x8c, 0x9d, 0x1d, 0xe2, 0x3d, 0x0e, 0x0e, 0xdc, 0x45, 0x22, 0x74,
	0x5b, 0x35, 0xef, 0xed, 0x2e, 0xc8, 0x3f, 0x70, 0x83, 0x7e, 0x47, 0xfa, 0x71, 0x13, 0xf4, 0xbc,
	0xa2, 0x64, 0x06, 0x83, 0x90, 0x31, 0x0a, 0xf8, 0x91, 0x46, 0x22, 0x89, 0x18, 0xfd, 0xd4, 0x93,
	0x08, 0x49, 0xe0, 0x33, 0xfa, 0xb9, 0x23, 0x81, 0xcf, 0x88, 0x0b, 0x36, 0xe3, 0x74, 0x8a, 0xc0,
	0x66, 0xdc, 0x38, 0xfc, 0x52, 0x50, 0xb7, 0x73, 0xf8, 0xa5, 0x30, 0x67, 0x49, 0x9b, 0xac, 0x69,
	0x35, 0xfd, 0xd2, 0x9d, 0xa5, 0xab, 0xc8, 0x37, 0x18, 0x9d, 0x29, 0x25, 0x15, 0x9d, 0x21, 0xee,
	0x0a, 0x8f, 0xc2, 0x30, 0x96, 0x75, 0x89, 0xb3, 0x75, 0x89, 0xff, 0xc5, 0xcc, 0xd6, 0xe5, 0xc9,
	0x83, 0x05, 0x4e, 0x20, 0xb3, 0x42, 0x28, 0x92, 0xc0, 0x2f, 0xa3, 0x8e, 0x6d, 0xfb, 0xdf, 0xe5,
	0xcb, 0x23, 0x39, 0x62, 0xf9, 0xe9, 0x6e, 0x2d, 0x66, 0x9c, 0xf7, 0xe1, 0x68, 0x66, 0xbf, 0x35,
	0x6f, 0x65, 0x76, 0x96, 0xfd, 0xcc, 0xdc, 0xc1, 0x37, 0x7a, 0xfa, 0x14, 0x00, 0x00, 0xff, 0xff,
	0x1d, 0xff, 0x3d, 0xcf, 0xb5, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LoaderClient is the client API for Loader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoaderClient interface {
	LoadMAPSubscriberInfoInvoke(ctx context.Context, in *MAPSubscriberInfoInvoke, opts ...grpc.CallOption) (*Pong, error)
	LoadMAPSubscriberInfoResult(ctx context.Context, in *MAPSubscriberInfoResult, opts ...grpc.CallOption) (*Pong, error)
}

type loaderClient struct {
	cc *grpc.ClientConn
}

func NewLoaderClient(cc *grpc.ClientConn) LoaderClient {
	return &loaderClient{cc}
}

func (c *loaderClient) LoadMAPSubscriberInfoInvoke(ctx context.Context, in *MAPSubscriberInfoInvoke, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, "/location.Loader/LoadMAPSubscriberInfoInvoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loaderClient) LoadMAPSubscriberInfoResult(ctx context.Context, in *MAPSubscriberInfoResult, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, "/location.Loader/LoadMAPSubscriberInfoResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoaderServer is the server API for Loader service.
type LoaderServer interface {
	LoadMAPSubscriberInfoInvoke(context.Context, *MAPSubscriberInfoInvoke) (*Pong, error)
	LoadMAPSubscriberInfoResult(context.Context, *MAPSubscriberInfoResult) (*Pong, error)
}

// UnimplementedLoaderServer can be embedded to have forward compatible implementations.
type UnimplementedLoaderServer struct {
}

func (*UnimplementedLoaderServer) LoadMAPSubscriberInfoInvoke(ctx context.Context, req *MAPSubscriberInfoInvoke) (*Pong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadMAPSubscriberInfoInvoke not implemented")
}
func (*UnimplementedLoaderServer) LoadMAPSubscriberInfoResult(ctx context.Context, req *MAPSubscriberInfoResult) (*Pong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadMAPSubscriberInfoResult not implemented")
}

func RegisterLoaderServer(s *grpc.Server, srv LoaderServer) {
	s.RegisterService(&_Loader_serviceDesc, srv)
}

func _Loader_LoadMAPSubscriberInfoInvoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MAPSubscriberInfoInvoke)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoaderServer).LoadMAPSubscriberInfoInvoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/location.Loader/LoadMAPSubscriberInfoInvoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoaderServer).LoadMAPSubscriberInfoInvoke(ctx, req.(*MAPSubscriberInfoInvoke))
	}
	return interceptor(ctx, in, info, handler)
}

func _Loader_LoadMAPSubscriberInfoResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MAPSubscriberInfoResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoaderServer).LoadMAPSubscriberInfoResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/location.Loader/LoadMAPSubscriberInfoResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoaderServer).LoadMAPSubscriberInfoResult(ctx, req.(*MAPSubscriberInfoResult))
	}
	return interceptor(ctx, in, info, handler)
}

var _Loader_serviceDesc = grpc.ServiceDesc{
	ServiceName: "location.Loader",
	HandlerType: (*LoaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadMAPSubscriberInfoInvoke",
			Handler:    _Loader_LoadMAPSubscriberInfoInvoke_Handler,
		},
		{
			MethodName: "LoadMAPSubscriberInfoResult",
			Handler:    _Loader_LoadMAPSubscriberInfoResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "location.proto",
}
